version: "3"

services:
  aria2web:
    build: .
    environment:
      - ARIA_RPC_SECRET=secret
      - ARIA_RPC_HOST=aria2dl
    ports:
      - 6800:80

  aria2dl:
    image: akisys/aria2.dl:latest
    environment:
      - ARIA_RPC_SECRET=secret
      - ARIA_DIR=/var/lib/seedbox
      - ARIA_MAX_CONCURRENT_DOWNLOADS=10
      - ARIA_ENABLE_DHT=false

